// GENERATED by scripts/build_buildings.py -- do not edit by hand.
// The demo area is defined once, in scripts/demo_area.py. See
// docs/05-map-milestone-plan.md section 3.

/** [south, west, north, east] in WGS84 degrees. */
export const DEMO_AREA_SWNE = [
  33.981, -118.2645, 33.996, -118.245,
] as const;

/** [west, south, east, north] -- the order MapLibre's fitBounds expects. */
export const DEMO_AREA_BOUNDS: [[number, number], [number, number]] = [
  [-118.2645, 33.981],
  [-118.245, 33.996],
];

export const DEMO_AREA_CENTER: [number, number] = [
  -118.25475, 33.9885,
];

/** The Beehive: the venue the demo area is built around. */
export const VENUE = {
  name: "The Beehive (SoLa Technology & Entrepreneurship Center)",
  lngLat: [-118.25747, 33.9853] as [number, number],
  councilDistrict: 9,
};

export const BUILDING_COUNT = 4887;

/** Served from web/public, so this is the browser-visible path. */
export const BUILDINGS_URL = "/data/buildings.geojson";
